# Generated by Django 5.1.2 on 2024-10-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=300)),
                ('tiempo_preparacion', models.TimeField()),
                ('categoria', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('numero_comensales', models.IntegerField()),
            ],
            options={
                'db_table': 'recetas',
                'managed': False,
            },
        ),
    ]
