# Generated by Django 5.1.2 on 2024-11-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id_pasos', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'pasos',
                'managed': False,
            },
        ),
    ]
