# Generated by Django 5.1.2 on 2024-10-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosificar',
            fields=[
                ('id_dosificar', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('numero_comensales', models.IntegerField()),
            ],
            options={
                'db_table': 'dosificar',
                'managed': False,
            },
        ),
    ]
